name: patient_data_mobile_app_milestone2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - gallery/Clinicalpatient.png
    - gallery/patientInfo.png
    - gallery/patient.png
    - gallery/ClinicalDataadd.png
    - gallery/updateClinicalData.png
    - gallery/updatePatient.png
    - gallery/view.png
    - gallery/ViewPatient.png
    - gallery/login.png
